# Generated by Django 3.1.5 on 2021-02-27 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendIt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='rating',
            field=models.ManyToManyField(related_name='raters', through='RecommendIt.Rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
